### ISSUE TITLE
Linux compatibility problem

### ISSUE THREAD

**Issue by stassius** [stassius/StableHoudini#3]
There is an error on Linux:

Traceback (most recent call last):
  File "Top/SD_Switch_Model, opdef:/Top/SD_Switch_Model?OnCreated, node /obj/topnet1/SD_Switch_Model1", line 1, in <module>
  File "Top/SD_Switch_Model, PythonModule", line 8, in RefreshModels
  File "/mnt/vfxserver01/Programs/houdini/19.5.403/houdini/python3.9libs/toolutils.py", line 1833, in createModuleFromSection
    return _createModule(module_name,
  File "/mnt/vfxserver01/Programs/houdini/19.5.403/houdini/python3.9libs/toolutils.py", line 1815, in _createModule
    eval(code, module_dict)
  File "SDA1111", line 2, in <module>
  File "/mnt/vfxserver01/Programs/houdini/19.5.403/python/lib/python3.9/site-packages-forced/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'msilib'

**Comment by stassius** [comment]
Resolved. Should work with the last commit.
