### ISSUE TITLE
[Problem]

### ISSUE THREAD

**Issue by FONGKA2** [stassius/StableHoudini#38]
Before filling the bug-report:

- [x] 1. Make sure you added --api key to the webui-user.bat
- [x] 2. Make sure you launched Automatic1111 with webui-user.bat
- [ ] 3. Check if Houdini is not blocked in your firewall
- [x] 4. Make sure you're using the right default URL in config.ini
- [x] 5. Check if the Automatic1111 is working in browser
- [x] 6. Try to find your error in this document: https://github.com/stassius/StableHoudini/wiki/Common-Errors

**Describe the bug**
Hello, i alrady do anything as i know to can to do, Houdini just cannot use the API
keep showing: Server returned: 500
i belive that i got some untend may small misstake
i already tried for a few days like force reinstall or changing some parts version of.

**Screenshots**
![aaa](https://github.com/stassius/StableHoudini/assets/1371202/265f30c4-fe75-4431-a520-eb7daa987430)

**Desktop (please complete the following information):**
 - OS: Win10 with Nvida(all in latest)
 - latest Automatic1111
 - latest Houdini

`API error: GET: http://127.0.0.1:7860/sdapi/v1/options {'error': 'ValidationError', 'detail': '', 'body': '', 'errors': '1 validation error for Options\nresponse -> sd_model_checkpoint\n  value is not None (type=type_error.not_none)'}
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\modules\api\api.py", line 152, in exception_handling
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\modules\api\api.py", line 117, in log_and_time
    res: Response = await call_next(req)
                    ^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\fastapi\routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Options
response -> sd_model_checkpoint
  value is not None (type=type_error.not_none)
API error: GET: http://127.0.0.1:7860/sdapi/v1/options {'error': 'ValidationError', 'detail': '', 'body': '', 'errors': '1 validation error for Options\nresponse -> sd_model_checkpoint\n  value is not None (type=type_error.not_none)'}
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\anyio\streams\memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\anyio\streams\memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\modules\api\api.py", line 152, in exception_handling
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\modules\api\api.py", line 117, in log_and_time
    res: Response = await call_next(req)
                    ^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\stable-diffusion-webui\venv\Lib\site-packages\fastapi\routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Options
response -> sd_model_checkpoint
  value is not None (type=type_error.not_none)`

**Comment by stassius** [comment]
@FONGKA2 Hello! When you put down SD Switch Model node, do you see the list of available models in the dropdown menu? If so, try to choose one of them and cook the node.

**Comment by FONGKA2** [comment]
> @FONGKA2 Hello! When you put down SD Switch Model node, do you see the list of available models in the dropdown menu? If so, try to choose one of them and cook the node.

Yes, i saw the models in the list menu, the error screenshot that's happen after i select a StableHoudini models, that's cause the 500 error and API error

**Comment by stassius** [comment]
@FONGKA2 Try other nodes, like SD Dream, SD Preprocessor, SD Upscale. Do they work?

**Comment by FONGKA2** [comment]
no, every node fail when i click them and return error500+api error

「stassius ***@***.***>」在 2023年6月26日 週一，下午4:13 寫道：

**Comment by stassius** [comment]
I've found a couple of mentions of the same error. One was from a person who got this error while using Automatic1111 in the cloud with https:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9013

Another one was from a person who uses a Chinese codepage:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9027#issuecomment-1484926437 

None of them were resolved, but you can try to contact these people and ask if they found the solution. 

If you have installed A1111 locally, I think it worth opening an issue in Automatic1111 repo, because it looks like an A1111 API bug to me. Maybe it has something to do with codepage, maybe something else.

**Comment by stassius** [comment]
@gfwfg Hello! What is your OS and codepage?

**Comment by gfwfg** [comment]
> @gfwfg Hello! What is your OS and codepage?

os : linux-x86-64
with api server
